### ISSUE TITLE
Compilation issues with latest cargo-rust

### ISSUE THREAD

**Issue by vlegakis** [MystenLabs/yubigen#4]
I upgraded rust-cargo to: cargo 1.80.0 (376290515 2024-07-16), rustc 1.80.0 (051478957 2024-07-21) and Yubigen doesn't compile :
(error[E0282]: type annotations needed for Box<_>
  --> ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.32/src/format_description/parse/mod.rs:83:9 
error: could not compile time (lib) due to 1 previous error

**Comment by chargarlic** [comment]
Hi @VLegakis thanks for raising this, i updated the dependencies with `cargo update` and that took care of it. Try pulling the latest changes!
